spring:
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: "http://127.0.0.1:9000"
      client:
        registration:
          frontend-app:
            provider: spring
            client-id: frontend-app
            client-secret: 12345
            authorization-grant-type: authorization_code
            redirect-uri: "http://127.0.0.1:9000/authorized"
            scope:
              - openid
              - profile
              - read
              - write
            client-name: frontend-app
        provider:
          spring:
            issuer-uri: "http://127.0.0.1:9000"



resilience4j.circuitbreaker:
  configs:
    default:
      slidingWindowSize: 6
      failureRateThreshold: 50
      waitDurationInOpenState: 20s
      permittedNumberOfCallsInHalfOpenState: 4
  instances:
    usersCircuitBreaker:
      base-config: default